[package]
name = "client"
version = "0.1.0"
authors = ["Herman Junge <herman@sigmaprime.io>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
client_backend = { path = "../backend", package = "backend" }
environment = { path = "../environment" }
futures = "0.3.5"
hyper = "0.13.5"
lazy_static = "1.4.0"
regex = "1.3.9"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.52"
slog = "2.5.2"
