[package]
name = "bls-remote-signer"
version = "0.1.0"
authors = ["Sigma Prime <contact@sigmaprime.io>"]
edition = "2018"

[dev-dependencies]
client_backend = { path = "./backend", package = "backend"  }
helpers = { path = "../testing/helpers", package = "helpers"  }

[dependencies]
clap = "2.33.3"
client = { path = "./client" }
environment = { path = "./environment" }
serde_json = "1.0.58"
slog = { version = "2.5.2", features = ["max_level_trace"] }
version = { path = "./version" }
