[package]
name = "backend"
version = "0.1.0"
authors = ["Herman Junge <herman@sigmaprime.io>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = { version = "1.0.110", features = ["derive"] }
slog = "2.5.2"
